import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";
import { google } from "googleapis";
import { Pool } from "pg";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PORT = Number(process.env.PORT) || 3000;

// =====================================================
// IMPORTANT
// Replace the connection string below with the EXACT
// Supabase URI from the Connect popup.
// Format:
// postgresql://USERNAME:PASSWORD@HOST:PORT/DATABASE
// =====================================================
const SUPABASE_CONNECTION_STRING =
  process.env.SUPABASE_CONNECTION_STRING ||
  "postgresql://postgres.xedztgzoyxgubbaxxbum:Abgrills2026!@aws-1-us-east-1.pooler.supabase.com:5432/postgres";

const pool = new Pool({
  connectionString: SUPABASE_CONNECTION_STRING,
  ssl: {
    rejectUnauthorized: false,
  },
});

// -------------------------
// Helpers
// -------------------------
function hashValue(value: string): string {
  return crypto.createHash("sha256").update(value).digest("hex");
}

async function getSetting(key: string): Promise<string | null> {
  const result = await pool.query(
    "SELECT value FROM settings WHERE key = $1 LIMIT 1",
    [key]
  );
  return result.rows[0]?.value ?? null;
}

async function setSetting(key: string, value: string): Promise<void> {
  await pool.query(
    `
    INSERT INTO settings (key, value)
    VALUES ($1, $2)
    ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
    `,
    [key, value]
  );
}

async function getAllSettings(): Promise<Record<string, string>> {
  const result = await pool.query("SELECT key, value FROM settings");
  const out: Record<string, string> = {};
  for (const row of result.rows) {
    out[row.key] = row.value;
  }
  return out;
}

// -------------------------
// PostgreSQL Init
// -------------------------
async function initPostgres() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS employees (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      role TEXT NOT NULL,
      pin TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'out',
      active INTEGER NOT NULL DEFAULT 1
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS shifts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      employee_id BIGINT NOT NULL,
      type TEXT NOT NULL,
      timestamp TIMESTAMPTZ NOT NULL,
      photo TEXT NOT NULL,
      latitude DOUBLE PRECISION,
      longitude DOUBLE PRECISION
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT
    );
  `);
}

// -------------------------
// Seed defaults
// -------------------------
async function seedPostgres() {
  if (!(await getSetting("admin_password"))) {
    await setSetting("admin_password", hashValue("admin123"));
    await setSetting("admin_username", "admin");
    await setSetting("admin_email", "abgrills001@gmail.com");
    await setSetting("restaurant_lat", "0");
    await setSetting("restaurant_lng", "0");
    await setSetting("allowed_radius", "100");
    await setSetting("google_sheets_token", "");
    await setSetting("admin_last_updated", new Date().toISOString());
    await setSetting("pg_config", "");
    await setSetting("last_pg_sync", "");
  }

  if ((await getSetting("admin_force_reset_done")) !== "1") {
    await setSetting("admin_username", "abgrills001@gmail.com");
    await setSetting("admin_password", hashValue("Abgrills2026@"));
    await setSetting("admin_email", "abgrills001@gmail.com");
    await setSetting("admin_last_updated", new Date().toISOString());
    await setSetting("admin_force_reset_done", "1");
  }

  const employeeCountResult = await pool.query(
    "SELECT COUNT(*)::int AS count FROM employees"
  );

  if ((employeeCountResult.rows[0]?.count ?? 0) === 0) {
    await pool.query(
      `
      INSERT INTO employees (name, role, pin, status, active)
      VALUES ($1, $2, $3, $4, $5)
      `,
      ["John Doe", "Server", "1234", "out", 1]
    );
  }
}

// -------------------------
// Auto Clock-out Logic
// -------------------------
let autoClockOutRunning = false;

setInterval(async () => {
  if (autoClockOutRunning) return;

  const now = new Date();
  if (now.getHours() === 23 && now.getMinutes() === 59) {
    autoClockOutRunning = true;

    try {
      const result = await pool.query(
        "SELECT id FROM employees WHERE status = 'in' AND active = 1"
      );

      for (const emp of result.rows) {
        const timestamp = new Date().toISOString();

        await pool.query(
          `
          INSERT INTO shifts (employee_id, type, timestamp, photo, latitude, longitude)
          VALUES ($1, $2, $3, $4, $5, $6)
          `,
          [emp.id, "out", timestamp, "AUTO_CLOCK_OUT", 0, 0]
        );

        await pool.query(
          "UPDATE employees SET status = 'out' WHERE id = $1",
          [emp.id]
        );
      }
    } catch (error) {
      console.error("[AUTO CLOCK-OUT ERROR]", error);
    } finally {
      autoClockOutRunning = false;
    }
  }
}, 60000);

async function startServer() {
  await initPostgres();
  await seedPostgres();

  const app = express();
  app.use(express.json({ limit: "10mb" }));

  // -------------------------
  // Auth
  // -------------------------
  app.post("/api/auth/employee", async (req, res) => {
    try {
      const { pin } = req.body;

      if (!pin) {
        return res.status(400).json({ error: "PIN is required" });
      }

      const result = await pool.query(
        "SELECT * FROM employees WHERE pin = $1 AND active = 1 LIMIT 1",
        [pin]
      );

      if (result.rows.length > 0) {
        return res.json(result.rows[0]);
      }

      return res.status(401).json({ error: "Invalid PIN" });
    } catch (error: any) {
      console.error("[EMPLOYEE AUTH ERROR]", error);
      return res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/auth/admin", async (req, res) => {
    try {
      const { username, password } = req.body;

      if (username === undefined || password === undefined) {
        return res.status(400).json({ error: "Username and password are required" });
      }

      const storedUser = await getSetting("admin_username");
      const storedPass = await getSetting("admin_password");

      if (!storedUser || !storedPass) {
        return res.status(500).json({ error: "Admin credentials are not configured" });
      }

      const hash = hashValue(password);

      if (username === storedUser && hash === storedPass) {
        return res.json({ success: true });
      }

      return res.status(401).json({ error: "Invalid credentials" });
    } catch (error: any) {
      console.error("[ADMIN AUTH ERROR]", error);
      return res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/auth/admin/reset", async (req, res) => {
    try {
      const adminEmail = (await getSetting("admin_email")) || "unknown@email.com";
      const newPassword = Math.random().toString(36).slice(-8);
      const hash = hashValue(newPassword);

      await setSetting("admin_password", hash);
      await setSetting("admin_last_updated", new Date().toISOString());

      return res.json({
        success: true,
        message: `A new password has been sent to ${adminEmail}. (Simulated: ${newPassword})`,
      });
    } catch (error: any) {
      console.error("[ADMIN RESET ERROR]", error);
      return res.status(500).json({ error: "Server error" });
    }
  });

  // -------------------------
  // Employees
  // -------------------------
  app.get("/api/employees", async (_req, res) => {
    try {
      const result = await pool.query(
        "SELECT * FROM employees WHERE active = 1 ORDER BY id ASC"
      );
      res.json(result.rows);
    } catch (error: any) {
      console.error("[GET EMPLOYEES ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/employees", async (req, res) => {
    try {
      const { name, role, pin } = req.body;

      if (!name || !role || !pin) {
        return res.status(400).json({ error: "name, role and pin are required" });
      }

      const result = await pool.query(
        `
        INSERT INTO employees (name, role, pin, status, active)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id
        `,
        [name, role, pin, "out", 1]
      );

      res.json({ id: result.rows[0].id });
    } catch (error: any) {
      console.error("[CREATE EMPLOYEE ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.put("/api/employees/:id", async (req, res) => {
    try {
      const { name, role, pin } = req.body;
      const { id } = req.params;

      if (!name || !role || !pin) {
        return res.status(400).json({ error: "name, role and pin are required" });
      }

      await pool.query(
        `
        UPDATE employees
        SET name = $1, role = $2, pin = $3
        WHERE id = $4
        `,
        [name, role, pin, id]
      );

      res.json({ success: true });
    } catch (error: any) {
      console.error("[UPDATE EMPLOYEE ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.delete("/api/employees/:id", async (req, res) => {
    try {
      const { id } = req.params;
      await pool.query("UPDATE employees SET active = 0 WHERE id = $1", [id]);
      res.json({ success: true });
    } catch (error: any) {
      console.error("[DELETE EMPLOYEE ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/employees/:id/clock-out", async (req, res) => {
    try {
      const { id } = req.params;
      const timestamp = new Date().toISOString();

      await pool.query(
        `
        INSERT INTO shifts (employee_id, type, timestamp, photo, latitude, longitude)
        VALUES ($1, $2, $3, $4, $5, $6)
        `,
        [id, "out", timestamp, "ADMIN_CLOCK_OUT", 0, 0]
      );

      await pool.query(
        "UPDATE employees SET status = 'out' WHERE id = $1",
        [id]
      );

      res.json({ success: true });
    } catch (error: any) {
      console.error("[ADMIN CLOCK-OUT ERROR]", error);
      res.status(500).json({ error: error.message });
    }
  });

  // -------------------------
  // Shifts
  // -------------------------
  app.get("/api/shifts", async (_req, res) => {
    try {
      const result = await pool.query(
        `
        SELECT s.*, e.name as employee_name
        FROM shifts s
        JOIN employees e ON s.employee_id = e.id
        ORDER BY s.timestamp DESC
        `
      );

      res.json(result.rows);
    } catch (error: any) {
      console.error("[GET SHIFTS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.get("/api/shifts/employee/:id", async (req, res) => {
    try {
      const { id } = req.params;

      const result = await pool.query(
        `
        SELECT * FROM shifts
        WHERE employee_id = $1
        ORDER BY timestamp DESC
        LIMIT 10
        `,
        [id]
      );

      res.json(result.rows);
    } catch (error: any) {
      console.error("[GET EMPLOYEE SHIFTS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/shifts", async (req, res) => {
    try {
      const { employee_id, type, photo, latitude, longitude } = req.body;

      if (!employee_id || !type || !photo) {
        return res.status(400).json({ error: "employee_id, type and photo are required" });
      }

      const timestamp = new Date().toISOString();

      await pool.query(
        `
        INSERT INTO shifts (employee_id, type, timestamp, photo, latitude, longitude)
        VALUES ($1, $2, $3, $4, $5, $6)
        `,
        [employee_id, type, timestamp, photo, latitude ?? null, longitude ?? null]
      );

      await pool.query(
        "UPDATE employees SET status = $1 WHERE id = $2",
        [type === "in" ? "in" : "out", employee_id]
      );

      res.json({ success: true });
    } catch (error: any) {
      console.error("[CREATE SHIFT ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.put("/api/shifts/:id", async (req, res) => {
    try {
      const { timestamp } = req.body;
      const { id } = req.params;

      if (!timestamp) {
        return res.status(400).json({ error: "timestamp is required" });
      }

      await pool.query(
        "UPDATE shifts SET timestamp = $1 WHERE id = $2",
        [timestamp, id]
      );

      res.json({ success: true });
    } catch (error: any) {
      console.error("[UPDATE SHIFT ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.delete("/api/shifts/:id", async (req, res) => {
    try {
      const { id } = req.params;

      const shiftResult = await pool.query(
        "SELECT employee_id FROM shifts WHERE id = $1 LIMIT 1",
        [id]
      );

      if (shiftResult.rows.length > 0) {
        const employeeId = shiftResult.rows[0].employee_id;

        await pool.query("DELETE FROM shifts WHERE id = $1", [id]);

        const latestShift = await pool.query(
          `
          SELECT type FROM shifts
          WHERE employee_id = $1
          ORDER BY timestamp DESC
          LIMIT 1
          `,
          [employeeId]
        );

        const newStatus =
          latestShift.rows.length > 0 && latestShift.rows[0].type === "in"
            ? "in"
            : "out";

        await pool.query(
          "UPDATE employees SET status = $1 WHERE id = $2",
          [newStatus, employeeId]
        );
      }

      res.json({ success: true });
    } catch (error: any) {
      console.error("[DELETE SHIFT ERROR]", error);
      res.status(500).json({ error: error.message });
    }
  });

  app.delete("/api/shifts", async (_req, res) => {
    try {
      await pool.query("DELETE FROM shifts");
      await pool.query("UPDATE employees SET status = 'out'");
      res.json({ success: true });
    } catch (error: any) {
      console.error("[DELETE ALL SHIFTS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  // -------------------------
  // Settings
  // -------------------------
  app.get("/api/settings", async (_req, res) => {
    try {
      const settings = await getAllSettings();
      delete settings.admin_password;
      res.json(settings);
    } catch (error: any) {
      console.error("[GET SETTINGS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.get("/api/debug/settings", async (_req, res) => {
    try {
      const settings = await getAllSettings();

      res.json({
        admin_username: settings.admin_username ?? null,
        admin_email: settings.admin_email ?? null,
        restaurant_lat: settings.restaurant_lat ?? null,
        restaurant_lng: settings.restaurant_lng ?? null,
        allowed_radius: settings.allowed_radius ?? null,
        admin_last_updated: settings.admin_last_updated ?? null,
        google_sheets_connected: !!settings.google_sheets_token,
        pg_config_present: !!settings.pg_config,
      });
    } catch (error: any) {
      console.error("[DEBUG SETTINGS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.put("/api/settings", async (req, res) => {
    try {
      const {
        restaurant_lat,
        restaurant_lng,
        allowed_radius,
        admin_password,
        admin_email,
        admin_username,
        pg_config,
        google_sheets_token,
      } = req.body;

      let adminUpdated = false;

      if (restaurant_lat !== undefined) {
        await setSetting("restaurant_lat", String(restaurant_lat));
      }

      if (restaurant_lng !== undefined) {
        await setSetting("restaurant_lng", String(restaurant_lng));
      }

      if (allowed_radius !== undefined) {
        await setSetting("allowed_radius", String(allowed_radius));
      }

      if (admin_email !== undefined) {
        await setSetting("admin_email", String(admin_email));
      }

      if (pg_config !== undefined) {
        await setSetting(
          "pg_config",
          typeof pg_config === "string" ? pg_config : JSON.stringify(pg_config)
        );
      }

      if (google_sheets_token !== undefined) {
        await setSetting("google_sheets_token", String(google_sheets_token));
      }

      if (admin_username !== undefined && String(admin_username).trim()) {
        await setSetting("admin_username", String(admin_username).trim());
        adminUpdated = true;
      }

      if (admin_password !== undefined && String(admin_password).trim()) {
        await setSetting("admin_password", hashValue(String(admin_password).trim()));
        adminUpdated = true;
      }

      if (adminUpdated) {
        await setSetting("admin_last_updated", new Date().toISOString());
      }

      const settings = await getAllSettings();
      delete settings.admin_password;

      res.json({
        success: true,
        last_updated: new Date().toISOString(),
        settings,
      });
    } catch (error: any) {
      console.error("[UPDATE SETTINGS ERROR]", error);
      res.status(500).json({ error: "Server error" });
    }
  });

  // -------------------------
  // Google Sheets Integration
  // -------------------------
  function getOAuth2Client() {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    let appUrl = process.env.APP_URL || "";

    if (appUrl.endsWith("/")) {
      appUrl = appUrl.slice(0, -1);
    }

    if (!clientId || !clientSecret) {
      return null;
    }

    return new google.auth.OAuth2(
      clientId,
      clientSecret,
      `${appUrl}/api/auth/google/callback`
    );
  }

  app.get("/api/debug/google-config", (_req, res) => {
    const keys = Object.keys(process.env);
    const hasId = !!process.env.GOOGLE_CLIENT_ID;
    const hasSecret = !!process.env.GOOGLE_CLIENT_SECRET;
    
    const typos = keys.filter(k => 
      (k.includes("GOOGLE") || k.includes("CLIENT")) && 
      k !== "GOOGLE_CLIENT_ID" && 
      k !== "GOOGLE_CLIENT_SECRET"
    );

    let appUrl = process.env.APP_URL || "";
    if (appUrl.endsWith("/")) appUrl = appUrl.slice(0, -1);
    const redirectUri = appUrl ? `${appUrl}/api/auth/google/callback` : "APP_URL not set";

    res.json({
      configured: hasId && hasSecret,
      missing: {
        GOOGLE_CLIENT_ID: !hasId,
        GOOGLE_CLIENT_SECRET: !hasSecret
      },
      detectedTypos: typos,
      redirectUri: redirectUri
    });
  });

  app.get("/api/auth/google/url", (_req, res) => {
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).json({
        error:
          "Google OAuth is not configured. Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the Secrets menu.",
      });
    }

    try {
      const url = client.generateAuthUrl({
        access_type: "offline",
        scope: ["https://www.googleapis.com/auth/spreadsheets"],
        prompt: "consent",
      });

      res.json({ url });
    } catch {
      res.status(500).json({ error: "Failed to generate auth URL" });
    }
  });

  app.get("/api/auth/google/callback", async (req, res) => {
    const { code } = req.query;
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).send("OAuth not configured");
    }

    try {
      const { tokens } = await client.getToken(code as string);
      await setSetting("google_sheets_token", JSON.stringify(tokens));

      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ type: 'OAUTH_AUTH_SUCCESS' }, '*');
                window.close();
              } else {
                window.location.href = '/admin';
              }
            </script>
            <p>Google Sheets connected! You can close this window.</p>
          </body>
        </html>
      `);
    } catch {
      res.status(500).send("Failed to connect to Google Sheets");
    }
  });

  app.post("/api/export/google-sheets", async (req, res) => {
    const { startDate, endDate } = req.body;
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).json({
        error:
          "Google OAuth is not configured. Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the Secrets menu.",
      });
    }

    const tokenValue = await getSetting("google_sheets_token");

    if (!tokenValue) {
      return res.status(401).json({
        error:
          "Google Sheets not connected. Please go to Settings and connect your account.",
      });
    }

    try {
      const tokens = JSON.parse(tokenValue);
      client.setCredentials(tokens);

      // Listen for token refreshes and save them
      client.on("tokens", async (newTokens) => {
        console.log("[GOOGLE SHEETS] Tokens refreshed, saving...");
        const currentTokens = JSON.parse((await getSetting("google_sheets_token")) || "{}");
        await setSetting("google_sheets_token", JSON.stringify({ ...currentTokens, ...newTokens }));
      });

      const sheets = google.sheets({ version: "v4", auth: client });

      console.log("[GOOGLE SHEETS] Creating spreadsheet...");
      const spreadsheet = await sheets.spreadsheets.create({
        requestBody: {
          properties: { title: `ShiftSnap Export ${new Date().toLocaleDateString()}` },
        },
      });

      const spreadsheetId = spreadsheet.data.spreadsheetId;
      if (!spreadsheetId) {
        throw new Error("Google API did not return a spreadsheet ID.");
      }
      console.log("[GOOGLE SHEETS] Spreadsheet created:", spreadsheetId);

      let query = `
        SELECT s.*, e.name as employee_name
        FROM shifts s
        JOIN employees e ON s.employee_id = e.id
      `;
      const params: any[] = [];

      if (startDate && endDate) {
        query += ` WHERE s.timestamp BETWEEN $1 AND $2 `;
        params.push(startDate, endDate);
      }

      query += ` ORDER BY s.timestamp DESC `;

      console.log("[GOOGLE SHEETS] Fetching shifts for export...");
      const shiftsResult =
        params.length > 0
          ? await pool.query(query, params)
          : await pool.query(query);

      const shifts = shiftsResult.rows;

      if (shifts.length === 0) {
        return res.status(400).json({
          error: "No shifts found for the selected date range. Please try a different range.",
        });
      }

      const values = [
        ["Employee", "Type", "Timestamp", "Latitude", "Longitude"],
        ...shifts.map((s) => [
          s.employee_name,
          String(s.type).toUpperCase(),
          s.timestamp instanceof Date ? s.timestamp.toISOString() : String(s.timestamp),
          s.latitude,
          s.longitude,
        ]),
      ];

      console.log("[GOOGLE SHEETS] Updating values...");
      await sheets.spreadsheets.values.update({
        spreadsheetId,
        range: "Sheet1!A1",
        valueInputOption: "RAW",
        requestBody: { values },
      });

      console.log("[GOOGLE SHEETS] Export successful");
      res.json({
        success: true,
        url: `https://docs.google.com/spreadsheets/d/${spreadsheetId}`,
      });
    } catch (error: any) {
      console.error("[GOOGLE SHEETS EXPORT ERROR]", error);
      console.error("[ERROR DETAILS]", JSON.stringify(error, null, 2));

      let message = "Failed to export to Google Sheets";
      if (error.message?.includes("invalid_grant")) {
        message = "Google connection expired. Please reconnect in Settings.";
      } else if (error.message?.includes("API has not been used") || error.message?.includes("not enabled")) {
        message = "Google Sheets API is not enabled in your Google Cloud Console.";
      } else if (error.code === 403) {
        message = "Permission denied. Please ensure the Google Sheets API is enabled and your account has access.";
      }

      res.status(500).json({ error: message, details: error.message });
    }
  });

  // -------------------------
  // PostgreSQL Sync
  // -------------------------
  app.post("/api/sync/postgres", async (_req, res) => {
    res.json({
      success: true,
      message: "This app now uses PostgreSQL as the main database.",
      last_sync: new Date().toISOString(),
    });
  });

  // -------------------------
  // Vite / Static
  // -------------------------
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });

    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(__dirname, "dist", "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch((error) => {
  console.error("[STARTUP ERROR]", error);
  process.exit(1);
});