import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";
import { google } from "googleapis";
import { Pool } from "pg";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PORT = Number(process.env.PORT) || 3000;

// =====================================================
// IMPORTANT
// Replace the connection string below with the EXACT
// Supabase URI from the Connect popup.
// Format:
// postgresql://USERNAME:PASSWORD@HOST:PORT/DATABASE
// =====================================================
const SUPABASE_CONNECTION_STRING =
  process.env.SUPABASE_CONNECTION_STRING ||
  "postgresql://postgres.xedztgzoyxgubbaxxbum:Abgrills2026!@aws-1-us-east-1.pooler.supabase.com:5432/postgres";

const pool = new Pool({
  connectionString: SUPABASE_CONNECTION_STRING,
  ssl: {
    rejectUnauthorized: false,
  },
});

// -------------------------
// Helpers
// -------------------------
function hashValue(value: string): string {
  return crypto.createHash("sha256").update(value).digest("hex");
}

async function getSetting(key: string): Promise<string | null> {
  const result = await pool.query(
    "SELECT value FROM settings WHERE key = $1 LIMIT 1",
    [key]
  );
  return result.rows[0]?.value ?? null;
}

async function setSetting(key: string, value: string): Promise<void> {
  await pool.query(
    `
    INSERT INTO settings (key, value)
    VALUES ($1, $2)
    ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
    `,
    [key, value]
  );
}

async function getAllSettings(): Promise<Record<string, string>> {
  const result = await pool.query("SELECT key, value FROM settings");
  const out: Record<string, string> = {};
  for (const row of result.rows) {
    out[row.key] = row.value;
  }
  return out;
}

// -------------------------
// PostgreSQL Init
// -------------------------
async function initPostgres() {
  // Ensure plain_password column exists
  try {
    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS plain_password TEXT");
  } catch (e) {
    // Ignore if already exists or other error
  }

  // Organizations
  await pool.query(`
    CREATE TABLE IF NOT EXISTS organizations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // Organization Settings
  await pool.query(`
    CREATE TABLE IF NOT EXISTS organization_settings (
      organization_id BIGINT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
      labels JSONB NOT NULL DEFAULT '{"staff": "Staff", "clockIn": "Clock In", "clockOut": "Clock Out", "location": "Location"}',
      branding JSONB NOT NULL DEFAULT '{"primaryColor": "#10b981"}',
      features JSONB NOT NULL DEFAULT '{"photoRequired": true, "geofencing": true, "pinLogin": true}',
      google_sheets_token TEXT,
      admin_email TEXT,
      admin_password TEXT
    );
  `);

  // Locations
  await pool.query(`
    CREATE TABLE IF NOT EXISTS locations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      address TEXT,
      latitude DOUBLE PRECISION NOT NULL,
      longitude DOUBLE PRECISION NOT NULL,
      radius_meters INTEGER NOT NULL DEFAULT 100
    );
  `);

  // Users (Refactored from employees)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT REFERENCES organizations(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      email TEXT,
      role TEXT NOT NULL DEFAULT 'staff',
      pin TEXT,
      status TEXT NOT NULL DEFAULT 'out',
      active INTEGER NOT NULL DEFAULT 1,
      password TEXT,
      plain_password TEXT
    );
  `);

  // Invites
  await pool.query(`
    CREATE TABLE IF NOT EXISTS invites (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      email TEXT NOT NULL,
      token TEXT UNIQUE NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      accepted_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // Shifts
  await pool.query(`
    CREATE TABLE IF NOT EXISTS shifts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      employee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
      type TEXT NOT NULL,
      timestamp TIMESTAMPTZ NOT NULL,
      photo TEXT NOT NULL,
      latitude DOUBLE PRECISION,
      longitude DOUBLE PRECISION
    );
  `);

  // Global Settings (for Super Admin)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT
    );
  `);

  // Migration: Move data from old tables if they exist
  try {
    const tableCheck = await pool.query("SELECT to_regclass('employees')");
    if (tableCheck.rows[0].to_regclass) {
      const orgCheck = await pool.query("SELECT id FROM organizations WHERE slug = 'default'");
      let defaultOrgId;
      if (orgCheck.rows.length === 0) {
        const newOrg = await pool.query(
          "INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id",
          ["Default Organization", "default"]
        );
        defaultOrgId = newOrg.rows[0].id;
        
        // Seed default settings
        const oldSettings = await getAllSettings();
        await pool.query(
          `INSERT INTO organization_settings (organization_id, admin_email, admin_password, google_sheets_token)
           VALUES ($1, $2, $3, $4)`,
          [defaultOrgId, oldSettings.admin_email || 'admin@example.com', oldSettings.admin_password || hashValue('admin123'), oldSettings.google_sheets_token || '']
        );

        // Create default location
        await pool.query(
          `INSERT INTO locations (organization_id, name, latitude, longitude, radius_meters)
           VALUES ($1, $2, $3, $4, $5)`,
          [defaultOrgId, "Main Office", parseFloat(oldSettings.restaurant_lat || "0"), parseFloat(oldSettings.restaurant_lng || "0"), parseInt(oldSettings.allowed_radius || "100")]
        );
      } else {
        defaultOrgId = orgCheck.rows[0].id;
      }

      // Migrate employees to users
      await pool.query(`
        INSERT INTO users (id, organization_id, name, role, pin, status, active)
        SELECT id, ${defaultOrgId}, name, 'staff', pin, status, active FROM employees
        ON CONFLICT (id) DO NOTHING
      `);

      // Migrate shifts
      await pool.query(`
        INSERT INTO shifts (id, organization_id, employee_id, type, timestamp, photo, latitude, longitude)
        SELECT id, ${defaultOrgId}, employee_id, type, timestamp, photo, latitude, longitude FROM shifts
        ON CONFLICT (id) DO NOTHING
      `);

      // Drop old tables after migration (optional, but safer to keep for a bit)
      // await pool.query("DROP TABLE employees, shifts CASCADE");
    }
  } catch (e) {
    console.error("Migration error:", e);
  }
}

// -------------------------
// Seed defaults
// -------------------------
async function seedPostgres() {
  // Super Admin
  if (!(await getSetting("super_admin_password"))) {
    await setSetting("super_admin_email", "abgrills001@gmail.com");
    await setSetting("super_admin_password", hashValue("Abgrills2026@"));
  }
}

// -------------------------
// Auto Clock-out Logic
// -------------------------
let autoClockOutRunning = false;

setInterval(async () => {
  if (autoClockOutRunning) return;

  const now = new Date();
  if (now.getHours() === 23 && now.getMinutes() === 59) {
    autoClockOutRunning = true;

    try {
      const result = await pool.query(
        "SELECT id, organization_id FROM users WHERE status = 'in' AND active = 1 AND role = 'staff'"
      );

      for (const emp of result.rows) {
        const timestamp = new Date().toISOString();

        await pool.query(
          `
          INSERT INTO shifts (organization_id, employee_id, type, timestamp, photo, latitude, longitude)
          VALUES ($1, $2, $3, $4, $5, $6, $7)
          `,
          [emp.organization_id, emp.id, "out", timestamp, "AUTO_CLOCK_OUT", 0, 0]
        );

        await pool.query(
          "UPDATE users SET status = 'out' WHERE id = $1",
          [emp.id]
        );
      }
    } catch (error) {
      console.error("[AUTO CLOCK-OUT ERROR]", error);
    } finally {
      autoClockOutRunning = false;
    }
  }
}, 60000);

async function startServer() {
  await initPostgres();
  await seedPostgres();

  const app = express();
  app.use(express.json({ limit: "10mb" }));

  // -------------------------
  // Auth & Middleware
  // -------------------------
  
  // Simple session-like check (in a real app, use JWT or express-session)
  // For this refactor, we'll expect organization_id in headers for admin routes
  // and derive it from the user object for staff routes.

  // -------------------------
  // Super Admin Routes
  // -------------------------
  app.post("/api/super/auth", async (req, res) => {
    const { email, password } = req.body;
    const storedEmail = await getSetting("super_admin_email");
    const storedPass = await getSetting("super_admin_password");

    if (email === storedEmail && hashValue(password) === storedPass) {
      return res.json({ success: true, role: 'super_admin' });
    }
    res.status(401).json({ error: "Invalid credentials" });
  });

  app.get("/api/super/organizations", async (req, res) => {
    try {
      const result = await pool.query("SELECT * FROM organizations ORDER BY created_at DESC");
      res.json(result.rows);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/super/organizations", async (req, res) => {
    const { name, slug } = req.body;
    try {
      const result = await pool.query(
        "INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING *",
        [name, slug]
      );
      const org = result.rows[0];
      await pool.query(
        "INSERT INTO organization_settings (organization_id) VALUES ($1)",
        [org.id]
      );
      res.json(org);
    } catch (error: any) {
      res.status(400).json({ error: error.message });
    }
  });

  app.get("/api/super/invites", async (req, res) => {
    try {
      const result = await pool.query("SELECT * FROM invites ORDER BY created_at DESC");
      res.json({
        invites: result.rows,
        appUrl: process.env.APP_URL || ""
      });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/super/invites", async (req, res) => {
    const { organization_id, email } = req.body;
    const token = crypto.randomBytes(32).toString('hex');
    const expires_at = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(); // 7 days

    try {
      await pool.query(
        "INSERT INTO invites (organization_id, email, token, expires_at) VALUES ($1, $2, $3, $4)",
        [organization_id, email, token, expires_at]
      );
      res.json({ success: true, token });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  app.get("/api/super/organizations/:id/admin", async (req, res) => {
    const { id } = req.params;
    try {
      const result = await pool.query(
        "SELECT id, name, email, plain_password FROM users WHERE organization_id = $1 AND role = 'admin' LIMIT 1",
        [id]
      );
      res.json(result.rows[0] || null);
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  app.post("/api/super/organizations/:id/admin", async (req, res) => {
    const { id } = req.params;
    const { email, password, name } = req.body;
    const normalizedEmail = email.trim().toLowerCase();
    try {
      // Check if admin exists
      const existing = await pool.query(
        "SELECT id FROM users WHERE organization_id = $1 AND role = 'admin' LIMIT 1",
        [id]
      );

      if (existing.rows.length > 0) {
        // Update
        await pool.query(
          "UPDATE users SET email = $1, password = $2, plain_password = $3, name = $4 WHERE id = $5",
          [normalizedEmail, hashValue(password), password, name || 'Admin', existing.rows[0].id]
        );
      } else {
        // Create
        await pool.query(
          `INSERT INTO users (organization_id, name, email, role, password, plain_password, active) 
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [id, name || 'Admin', normalizedEmail, 'admin', hashValue(password), password, 1]
        );
      }
      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  app.post("/api/super/login-as/:orgId", async (req, res) => {
    const { orgId } = req.params;
    try {
      const result = await pool.query(
        "SELECT * FROM users WHERE organization_id = $1 AND role = 'admin' AND active = 1 LIMIT 1",
        [orgId]
      );
      if (result.rows.length === 0) {
        return res.status(404).json({ error: "No admin found for this organization" });
      }
      const user = result.rows[0];
      const settings = await pool.query("SELECT * FROM organization_settings WHERE organization_id = $1", [user.organization_id]);
      res.json({ success: true, user, settings: settings.rows[0] });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  app.patch("/api/super/organizations/:id", async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;
    try {
      await pool.query("UPDATE organizations SET status = $1 WHERE id = $2", [status, id]);
      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  app.delete("/api/super/invites/:token", async (req, res) => {
    const { token } = req.params;
    try {
      await pool.query("DELETE FROM invites WHERE token = $1", [token]);
      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  // -------------------------
  // Sub Admin Setup Routes
  // -------------------------
  app.get("/api/setup/validate/:token", async (req, res) => {
    const { token } = req.params;
    try {
      const result = await pool.query(
        `SELECT i.*, o.name as organization_name 
         FROM invites i 
         JOIN organizations o ON i.organization_id = o.id 
         WHERE i.token = $1 AND i.accepted_at IS NULL AND i.expires_at > NOW()`,
        [token]
      );
      if (result.rows.length === 0) return res.status(404).json({ error: "Invalid or expired token" });
      res.json(result.rows[0]);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/setup/complete", async (req, res) => {
    const { token, password, name, businessName, location } = req.body;
    try {
      const inviteResult = await pool.query("SELECT * FROM invites WHERE token = $1", [token]);
      if (inviteResult.rows.length === 0) return res.status(404).json({ error: "Invalid token" });
      const invite = inviteResult.rows[0];

      // Update organization name if changed
      await pool.query("UPDATE organizations SET name = $1 WHERE id = $2", [businessName, invite.organization_id]);

      // Create Admin User
      const normalizedEmail = invite.email.trim().toLowerCase();
      await pool.query(
        `INSERT INTO users (organization_id, name, email, role, password, plain_password, active) 
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [invite.organization_id, name, normalizedEmail, 'admin', hashValue(password), password, 1]
      );

      // Create First Location
      await pool.query(
        `INSERT INTO locations (organization_id, name, address, latitude, longitude, radius_meters) 
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [invite.organization_id, location.name, location.address, location.lat, location.lng, 100]
      );

      // Mark invite as accepted
      await pool.query("UPDATE invites SET accepted_at = NOW() WHERE id = $1", [invite.id]);

      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  // -------------------------
  // Sub Admin Routes
  // -------------------------
  app.post("/api/auth/admin", async (req, res) => {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: "Email and password required" });
    
    const normalizedEmail = email.trim().toLowerCase();
    const trimmedPassword = password.trim(); // Some users accidentally add spaces
    
    try {
      // Fetch all active admin users with this email and their organization status
      const result = await pool.query(
        `SELECT u.*, o.status as org_status, o.name as org_name
         FROM users u 
         JOIN organizations o ON u.organization_id = o.id
         WHERE LOWER(TRIM(u.email)) = $1 AND u.role = 'admin' AND u.active = 1`,
        [normalizedEmail]
      );

      console.log(`Login attempt for ${normalizedEmail}. Found ${result.rows.length} accounts.`);

      if (result.rows.length === 0) {
        return res.status(401).json({ error: "Invalid credentials" });
      }

      // Find the user with the matching password (check both hashed and trimmed hashed)
      const hashedInput = hashValue(trimmedPassword);
      const hashedRawInput = hashValue(password);
      
      const user = result.rows.find(row => 
        row.password === hashedInput || 
        row.password === hashedRawInput ||
        row.password === trimmedPassword ||
        row.password === password ||
        row.plain_password === trimmedPassword ||
        row.plain_password === password
      );

      if (!user) {
        console.log(`Password mismatch for ${normalizedEmail}`);
        return res.status(401).json({ error: "Invalid credentials" });
      }

      // Check if organization is active
      if (user.org_status !== 'active') {
        return res.status(403).json({ error: `Organization "${user.org_name}" is suspended. Please contact support.` });
      }

      const settings = await pool.query("SELECT * FROM organization_settings WHERE organization_id = $1", [user.organization_id]);
      console.log(`Login successful for ${normalizedEmail} (Org: ${user.org_name})`);
      return res.json({ success: true, user, settings: settings.rows[0] });
    } catch (error) {
      console.error('Login error:', error);
      res.status(500).json({ error: "Server error" });
    }
  });

  app.get("/api/admin/settings", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    try {
      const result = await pool.query("SELECT * FROM organization_settings WHERE organization_id = $1", [orgId]);
      res.json(result.rows[0]);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.put("/api/admin/settings", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const { labels, branding, features, google_sheets_token } = req.body;
    try {
      await pool.query(
        `UPDATE organization_settings 
         SET labels = $1, branding = $2, features = $3, google_sheets_token = $4 
         WHERE organization_id = $5`,
        [JSON.stringify(labels), JSON.stringify(branding), JSON.stringify(features), google_sheets_token, orgId]
      );
      res.json({ success: true });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.get("/api/admin/staff", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    try {
      const result = await pool.query(
        "SELECT * FROM users WHERE organization_id = $1 AND role = 'staff' AND active = 1 ORDER BY name ASC",
        [orgId]
      );
      res.json(result.rows);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/admin/staff", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const { name, role, pin } = req.body;
    try {
      const result = await pool.query(
        "INSERT INTO users (organization_id, name, role, pin, active) VALUES ($1, $2, $3, $4, 1) RETURNING id",
        [orgId, name, role, pin]
      );
      res.json({ id: result.rows[0].id });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.get("/api/admin/locations", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    try {
      const result = await pool.query("SELECT * FROM locations WHERE organization_id = $1", [orgId]);
      res.json(result.rows);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/admin/locations", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const { name, address, latitude, longitude, radius_meters } = req.body;
    try {
      const result = await pool.query(
        "INSERT INTO locations (organization_id, name, address, latitude, longitude, radius_meters) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id",
        [orgId, name, address, latitude, longitude, radius_meters]
      );
      res.json({ id: result.rows[0].id });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  // -------------------------
  // Staff Routes
  // -------------------------
  app.get("/api/staff/config/:slug", async (req, res) => {
    const { slug } = req.params;
    try {
      const orgResult = await pool.query("SELECT id, name FROM organizations WHERE slug = $1", [slug]);
      if (orgResult.rows.length === 0) return res.status(404).json({ error: "Organization not found" });
      const org = orgResult.rows[0];
      const settings = await pool.query("SELECT labels, branding, features FROM organization_settings WHERE organization_id = $1", [org.id]);
      const locations = await pool.query("SELECT * FROM locations WHERE organization_id = $1", [org.id]);
      res.json({ organization: org, settings: settings.rows[0], locations: locations.rows });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/auth/employee", async (req, res) => {
    const { pin, organization_id } = req.body;
    try {
      const result = await pool.query(
        "SELECT * FROM users WHERE pin = $1 AND organization_id = $2 AND active = 1 LIMIT 1",
        [pin, organization_id]
      );
      if (result.rows.length > 0) return res.json(result.rows[0]);
      res.status(401).json({ error: "Invalid PIN" });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.post("/api/staff/clock", async (req, res) => {
    const { user_id, organization_id, location_id, type, photo, latitude, longitude } = req.body;
    try {
      const timestamp = new Date().toISOString();
      await pool.query(
        `INSERT INTO shifts (organization_id, employee_id, location_id, type, timestamp, photo, latitude, longitude) 
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
        [organization_id, user_id, location_id, type, timestamp, photo, latitude, longitude]
      );
      await pool.query("UPDATE users SET status = $1 WHERE id = $2", [type, user_id]);
      res.json({ success: true });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  // -------------------------
  // Legacy / Shared Routes (Updated for multi-tenancy)
  // -------------------------
  app.get("/api/shifts", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    try {
      const result = await pool.query(
        `SELECT s.*, u.name as employee_name 
         FROM shifts s 
         JOIN users u ON s.employee_id = u.id 
         WHERE s.organization_id = $1 
         ORDER BY s.timestamp DESC`,
        [orgId]
      );
      res.json(result.rows);
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  app.delete("/api/shifts/:id", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const { id } = req.params;
    try {
      await pool.query("DELETE FROM shifts WHERE id = $1 AND organization_id = $2", [id, orgId]);
      res.json({ success: true });
    } catch (error) {
      res.status(500).json({ error: "Server error" });
    }
  });

  // ... (Keep other routes like Google Sheets but update them to use organization_id)

  // -------------------------
  // Google Sheets Integration
  // -------------------------
  function getOAuth2Client() {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    let appUrl = process.env.APP_URL || "";

    if (appUrl.endsWith("/")) {
      appUrl = appUrl.slice(0, -1);
    }

    if (!clientId || !clientSecret) {
      return null;
    }

    return new google.auth.OAuth2(
      clientId,
      clientSecret,
      `${appUrl}/api/auth/google/callback`
    );
  }

  app.get("/api/debug/google-config", (_req, res) => {
    const keys = Object.keys(process.env);
    const hasId = !!process.env.GOOGLE_CLIENT_ID;
    const hasSecret = !!process.env.GOOGLE_CLIENT_SECRET;
    
    const typos = keys.filter(k => 
      (k.includes("GOOGLE") || k.includes("CLIENT")) && 
      k !== "GOOGLE_CLIENT_ID" && 
      k !== "GOOGLE_CLIENT_SECRET"
    );

    let appUrl = process.env.APP_URL || "";
    if (appUrl.endsWith("/")) appUrl = appUrl.slice(0, -1);
    const redirectUri = appUrl ? `${appUrl}/api/auth/google/callback` : "APP_URL not set";

    res.json({
      configured: hasId && hasSecret,
      missing: {
        GOOGLE_CLIENT_ID: !hasId,
        GOOGLE_CLIENT_SECRET: !hasSecret
      },
      detectedTypos: typos,
      redirectUri: redirectUri
    });
  });

  app.get("/api/auth/google/url", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).json({
        error:
          "Google OAuth is not configured. Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the Secrets menu.",
      });
    }

    try {
      const url = client.generateAuthUrl({
        access_type: "offline",
        scope: ["https://www.googleapis.com/auth/spreadsheets"],
        prompt: "consent",
        state: orgId?.toString() // Pass orgId in state
      });

      res.json({ url });
    } catch {
      res.status(500).json({ error: "Failed to generate auth URL" });
    }
  });

  app.get("/api/auth/google/callback", async (req, res) => {
    const { code, state: orgId } = req.query;
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).send("OAuth not configured");
    }

    try {
      const { tokens } = await client.getToken(code as string);
      
      // Store token in organization_settings
      await pool.query(
        "UPDATE organization_settings SET google_sheets_token = $1 WHERE organization_id = $2",
        [JSON.stringify(tokens), orgId]
      );

      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ type: 'OAUTH_AUTH_SUCCESS' }, '*');
                window.close();
              } else {
                window.location.href = '/admin';
              }
            </script>
            <p>Google Sheets connected! You can close this window.</p>
          </body>
        </html>
      `);
    } catch (error) {
      console.error("Google callback error:", error);
      res.status(500).send("Failed to connect to Google Sheets");
    }
  });

  app.post("/api/export/google-sheets", async (req, res) => {
    const orgId = req.headers['x-organization-id'];
    const { startDate, endDate } = req.body;
    const client = getOAuth2Client();

    if (!client) {
      return res.status(400).json({
        error:
          "Google OAuth is not configured. Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the Secrets menu.",
      });
    }

    const result = await pool.query("SELECT google_sheets_token FROM organization_settings WHERE organization_id = $1", [orgId]);
    const tokenValue = result.rows[0]?.google_sheets_token;

    if (!tokenValue) {
      return res.status(401).json({
        error:
          "Google Sheets not connected. Please go to Settings and connect your account.",
      });
    }

    try {
      const tokens = JSON.parse(tokenValue);
      client.setCredentials(tokens);

      client.on("tokens", async (newTokens) => {
        console.log("[GOOGLE SHEETS] Tokens refreshed, saving...");
        const currentResult = await pool.query("SELECT google_sheets_token FROM organization_settings WHERE organization_id = $1", [orgId]);
        const currentTokens = JSON.parse(currentResult.rows[0]?.google_sheets_token || "{}");
        await pool.query(
          "UPDATE organization_settings SET google_sheets_token = $1 WHERE organization_id = $2",
          [JSON.stringify({ ...currentTokens, ...newTokens }), orgId]
        );
      });

      const sheets = google.sheets({ version: "v4", auth: client });

      console.log("[GOOGLE SHEETS] Creating spreadsheet...");
      const spreadsheet = await sheets.spreadsheets.create({
        requestBody: {
          properties: { title: `ShiftSnap Export ${new Date().toLocaleDateString()}` },
        },
      });

      const spreadsheetId = spreadsheet.data.spreadsheetId;
      if (!spreadsheetId) {
        throw new Error("Google API did not return a spreadsheet ID.");
      }
      
      let query = `
        SELECT s.*, u.name as employee_name
        FROM shifts s
        JOIN users u ON s.employee_id = u.id
        WHERE s.organization_id = $1
      `;
      const params: any[] = [orgId];

      if (startDate && endDate) {
        query += ` AND s.timestamp BETWEEN $2 AND $3 `;
        params.push(startDate, endDate);
      }

      query += ` ORDER BY s.timestamp DESC `;

      const shiftsResult = await pool.query(query, params);
      const shifts = shiftsResult.rows;

      if (shifts.length === 0) {
        return res.status(400).json({
          error: "No shifts found for the selected date range.",
        });
      }

      const values = [
        ["Employee", "Type", "Timestamp", "Latitude", "Longitude"],
        ...shifts.map((s) => [
          s.employee_name,
          String(s.type).toUpperCase(),
          s.timestamp instanceof Date ? s.timestamp.toISOString() : String(s.timestamp),
          s.latitude,
          s.longitude,
        ]),
      ];

      await sheets.spreadsheets.values.update({
        spreadsheetId,
        range: "Sheet1!A1",
        valueInputOption: "RAW",
        requestBody: { values },
      });

      res.json({
        success: true,
        url: `https://docs.google.com/spreadsheets/d/${spreadsheetId}`,
      });
    } catch (error: any) {
      console.error("[GOOGLE SHEETS EXPORT ERROR]", error);
      res.status(500).json({ error: "Failed to export to Google Sheets", details: error.message });
    }
  });

  // -------------------------
  // PostgreSQL Sync
  // -------------------------
  app.post("/api/sync/postgres", async (_req, res) => {
    res.json({
      success: true,
      message: "This app now uses PostgreSQL as the main database.",
      last_sync: new Date().toISOString(),
    });
  });

  // -------------------------
  // Vite / Static
  // -------------------------
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });

    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(__dirname, "dist", "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch((error) => {
  console.error("[STARTUP ERROR]", error);
  process.exit(1);
});